#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("OxHack.Inventory.MobileClient.Droid.Resource", IsApplication=true)]

namespace OxHack.Inventory.MobileClient.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AndroidHUD.Resource.Attribute.ahBarColor = global::OxHack.Inventory.MobileClient.Droid.Resource.Attribute.ahBarColor;
			global::AndroidHUD.Resource.Attribute.ahBarLength = global::OxHack.Inventory.MobileClient.Droid.Resource.Attribute.ahBarLength;
			global::AndroidHUD.Resource.Attribute.ahBarWidth = global::OxHack.Inventory.MobileClient.Droid.Resource.Attribute.ahBarWidth;
			global::AndroidHUD.Resource.Attribute.ahCircleColor = global::OxHack.Inventory.MobileClient.Droid.Resource.Attribute.ahCircleColor;
			global::AndroidHUD.Resource.Attribute.ahDelayMillis = global::OxHack.Inventory.MobileClient.Droid.Resource.Attribute.ahDelayMillis;
			global::AndroidHUD.Resource.Attribute.ahRadius = global::OxHack.Inventory.MobileClient.Droid.Resource.Attribute.ahRadius;
			global::AndroidHUD.Resource.Attribute.ahRimColor = global::OxHack.Inventory.MobileClient.Droid.Resource.Attribute.ahRimColor;
			global::AndroidHUD.Resource.Attribute.ahRimWidth = global::OxHack.Inventory.MobileClient.Droid.Resource.Attribute.ahRimWidth;
			global::AndroidHUD.Resource.Attribute.ahSpinSpeed = global::OxHack.Inventory.MobileClient.Droid.Resource.Attribute.ahSpinSpeed;
			global::AndroidHUD.Resource.Attribute.ahText = global::OxHack.Inventory.MobileClient.Droid.Resource.Attribute.ahText;
			global::AndroidHUD.Resource.Attribute.ahTextColor = global::OxHack.Inventory.MobileClient.Droid.Resource.Attribute.ahTextColor;
			global::AndroidHUD.Resource.Attribute.ahTextSize = global::OxHack.Inventory.MobileClient.Droid.Resource.Attribute.ahTextSize;
			global::AndroidHUD.Resource.Drawable.ic_errorstatus = global::OxHack.Inventory.MobileClient.Droid.Resource.Drawable.ic_errorstatus;
			global::AndroidHUD.Resource.Drawable.ic_successstatus = global::OxHack.Inventory.MobileClient.Droid.Resource.Drawable.ic_successstatus;
			global::AndroidHUD.Resource.Drawable.roundedbg = global::OxHack.Inventory.MobileClient.Droid.Resource.Drawable.roundedbg;
			global::AndroidHUD.Resource.Drawable.roundedbgdark = global::OxHack.Inventory.MobileClient.Droid.Resource.Drawable.roundedbgdark;
			global::AndroidHUD.Resource.Id.loadingImage = global::OxHack.Inventory.MobileClient.Droid.Resource.Id.loadingImage;
			global::AndroidHUD.Resource.Id.loadingProgressBar = global::OxHack.Inventory.MobileClient.Droid.Resource.Id.loadingProgressBar;
			global::AndroidHUD.Resource.Id.loadingProgressWheel = global::OxHack.Inventory.MobileClient.Droid.Resource.Id.loadingProgressWheel;
			global::AndroidHUD.Resource.Id.textViewStatus = global::OxHack.Inventory.MobileClient.Droid.Resource.Id.textViewStatus;
			global::AndroidHUD.Resource.Layout.loading = global::OxHack.Inventory.MobileClient.Droid.Resource.Layout.loading;
			global::AndroidHUD.Resource.Layout.loadingimage = global::OxHack.Inventory.MobileClient.Droid.Resource.Layout.loadingimage;
			global::AndroidHUD.Resource.Layout.loadingprogress = global::OxHack.Inventory.MobileClient.Droid.Resource.Layout.loadingprogress;
			global::AndroidHUD.Resource.String.library_name = global::OxHack.Inventory.MobileClient.Droid.Resource.String.library_name;
			global::AndroidHUD.Resource.Styleable.ProgressWheel = global::OxHack.Inventory.MobileClient.Droid.Resource.Styleable.ProgressWheel;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarColor = global::OxHack.Inventory.MobileClient.Droid.Resource.Styleable.ProgressWheel_ahBarColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarLength = global::OxHack.Inventory.MobileClient.Droid.Resource.Styleable.ProgressWheel_ahBarLength;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarWidth = global::OxHack.Inventory.MobileClient.Droid.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahCircleColor = global::OxHack.Inventory.MobileClient.Droid.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahDelayMillis = global::OxHack.Inventory.MobileClient.Droid.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRadius = global::OxHack.Inventory.MobileClient.Droid.Resource.Styleable.ProgressWheel_ahRadius;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimColor = global::OxHack.Inventory.MobileClient.Droid.Resource.Styleable.ProgressWheel_ahRimColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimWidth = global::OxHack.Inventory.MobileClient.Droid.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::OxHack.Inventory.MobileClient.Droid.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahText = global::OxHack.Inventory.MobileClient.Droid.Resource.Styleable.ProgressWheel_ahText;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextColor = global::OxHack.Inventory.MobileClient.Droid.Resource.Styleable.ProgressWheel_ahTextColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextSize = global::OxHack.Inventory.MobileClient.Droid.Resource.Styleable.ProgressWheel_ahTextSize;
			global::HockeyApp.Resource.Color.hockeyapp_background_header = global::OxHack.Inventory.MobileClient.Droid.Resource.Color.hockeyapp_background_header;
			global::HockeyApp.Resource.Color.hockeyapp_background_light = global::OxHack.Inventory.MobileClient.Droid.Resource.Color.hockeyapp_background_light;
			global::HockeyApp.Resource.Color.hockeyapp_background_white = global::OxHack.Inventory.MobileClient.Droid.Resource.Color.hockeyapp_background_white;
			global::HockeyApp.Resource.Color.hockeyapp_button_background = global::OxHack.Inventory.MobileClient.Droid.Resource.Color.hockeyapp_button_background;
			global::HockeyApp.Resource.Color.hockeyapp_button_background_pressed = global::OxHack.Inventory.MobileClient.Droid.Resource.Color.hockeyapp_button_background_pressed;
			global::HockeyApp.Resource.Color.hockeyapp_button_background_selected = global::OxHack.Inventory.MobileClient.Droid.Resource.Color.hockeyapp_button_background_selected;
			global::HockeyApp.Resource.Color.hockeyapp_text_black = global::OxHack.Inventory.MobileClient.Droid.Resource.Color.hockeyapp_text_black;
			global::HockeyApp.Resource.Color.hockeyapp_text_light = global::OxHack.Inventory.MobileClient.Droid.Resource.Color.hockeyapp_text_light;
			global::HockeyApp.Resource.Color.hockeyapp_text_normal = global::OxHack.Inventory.MobileClient.Droid.Resource.Color.hockeyapp_text_normal;
			global::HockeyApp.Resource.Color.hockeyapp_text_white = global::OxHack.Inventory.MobileClient.Droid.Resource.Color.hockeyapp_text_white;
			global::HockeyApp.Resource.Drawable.hockeyapp_btn_background = global::OxHack.Inventory.MobileClient.Droid.Resource.Drawable.hockeyapp_btn_background;
			global::HockeyApp.Resource.Id.button_add_response = global::OxHack.Inventory.MobileClient.Droid.Resource.Id.button_add_response;
			global::HockeyApp.Resource.Id.button_attachment = global::OxHack.Inventory.MobileClient.Droid.Resource.Id.button_attachment;
			global::HockeyApp.Resource.Id.button_login = global::OxHack.Inventory.MobileClient.Droid.Resource.Id.button_login;
			global::HockeyApp.Resource.Id.button_refresh = global::OxHack.Inventory.MobileClient.Droid.Resource.Id.button_refresh;
			global::HockeyApp.Resource.Id.button_send = global::OxHack.Inventory.MobileClient.Droid.Resource.Id.button_send;
			global::HockeyApp.Resource.Id.button_update = global::OxHack.Inventory.MobileClient.Droid.Resource.Id.button_update;
			global::HockeyApp.Resource.Id.input_email = global::OxHack.Inventory.MobileClient.Droid.Resource.Id.input_email;
			global::HockeyApp.Resource.Id.input_message = global::OxHack.Inventory.MobileClient.Droid.Resource.Id.input_message;
			global::HockeyApp.Resource.Id.input_name = global::OxHack.Inventory.MobileClient.Droid.Resource.Id.input_name;
			global::HockeyApp.Resource.Id.input_password = global::OxHack.Inventory.MobileClient.Droid.Resource.Id.input_password;
			global::HockeyApp.Resource.Id.input_subject = global::OxHack.Inventory.MobileClient.Droid.Resource.Id.input_subject;
			global::HockeyApp.Resource.Id.label_author = global::OxHack.Inventory.MobileClient.Droid.Resource.Id.label_author;
			global::HockeyApp.Resource.Id.label_date = global::OxHack.Inventory.MobileClient.Droid.Resource.Id.label_date;
			global::HockeyApp.Resource.Id.label_last_updated = global::OxHack.Inventory.MobileClient.Droid.Resource.Id.label_last_updated;
			global::HockeyApp.Resource.Id.label_message = global::OxHack.Inventory.MobileClient.Droid.Resource.Id.label_message;
			global::HockeyApp.Resource.Id.label_text = global::OxHack.Inventory.MobileClient.Droid.Resource.Id.label_text;
			global::HockeyApp.Resource.Id.label_title = global::OxHack.Inventory.MobileClient.Droid.Resource.Id.label_title;
			global::HockeyApp.Resource.Id.label_version = global::OxHack.Inventory.MobileClient.Droid.Resource.Id.label_version;
			global::HockeyApp.Resource.Id.list_attachments = global::OxHack.Inventory.MobileClient.Droid.Resource.Id.list_attachments;
			global::HockeyApp.Resource.Id.list_feedback_messages = global::OxHack.Inventory.MobileClient.Droid.Resource.Id.list_feedback_messages;
			global::HockeyApp.Resource.Id.text_headline = global::OxHack.Inventory.MobileClient.Droid.Resource.Id.text_headline;
			global::HockeyApp.Resource.Id.view_header = global::OxHack.Inventory.MobileClient.Droid.Resource.Id.view_header;
			global::HockeyApp.Resource.Id.web_update_details = global::OxHack.Inventory.MobileClient.Droid.Resource.Id.web_update_details;
			global::HockeyApp.Resource.Id.wrapper_attachments = global::OxHack.Inventory.MobileClient.Droid.Resource.Id.wrapper_attachments;
			global::HockeyApp.Resource.Id.wrapper_feedback = global::OxHack.Inventory.MobileClient.Droid.Resource.Id.wrapper_feedback;
			global::HockeyApp.Resource.Id.wrapper_feedback_scroll = global::OxHack.Inventory.MobileClient.Droid.Resource.Id.wrapper_feedback_scroll;
			global::HockeyApp.Resource.Id.wrapper_messages = global::OxHack.Inventory.MobileClient.Droid.Resource.Id.wrapper_messages;
			global::HockeyApp.Resource.Id.wrapper_messages_buttons = global::OxHack.Inventory.MobileClient.Droid.Resource.Id.wrapper_messages_buttons;
			global::HockeyApp.Resource.Layout.hockeyapp_activity_expiry_info = global::OxHack.Inventory.MobileClient.Droid.Resource.Layout.hockeyapp_activity_expiry_info;
			global::HockeyApp.Resource.Layout.hockeyapp_activity_feedback = global::OxHack.Inventory.MobileClient.Droid.Resource.Layout.hockeyapp_activity_feedback;
			global::HockeyApp.Resource.Layout.hockeyapp_activity_login = global::OxHack.Inventory.MobileClient.Droid.Resource.Layout.hockeyapp_activity_login;
			global::HockeyApp.Resource.Layout.hockeyapp_activity_update = global::OxHack.Inventory.MobileClient.Droid.Resource.Layout.hockeyapp_activity_update;
			global::HockeyApp.Resource.Layout.hockeyapp_fragment_update = global::OxHack.Inventory.MobileClient.Droid.Resource.Layout.hockeyapp_fragment_update;
			global::HockeyApp.Resource.Layout.hockeyapp_view_feedback_message = global::OxHack.Inventory.MobileClient.Droid.Resource.Layout.hockeyapp_view_feedback_message;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_app_name_fallback = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_crash_dialog_app_name_fallback;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_message = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_crash_dialog_message;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_negative_button = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_crash_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_neutral_button = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_crash_dialog_neutral_button;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_positive_button = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_crash_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_title = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_crash_dialog_title;
			global::HockeyApp.Resource.String.hockeyapp_dialog_error_message = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_dialog_error_message;
			global::HockeyApp.Resource.String.hockeyapp_dialog_error_title = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_dialog_error_title;
			global::HockeyApp.Resource.String.hockeyapp_dialog_negative_button = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_dialog_positive_button = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_download_failed_dialog_message = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_download_failed_dialog_message;
			global::HockeyApp.Resource.String.hockeyapp_download_failed_dialog_negative_button = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_download_failed_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_download_failed_dialog_positive_button = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_download_failed_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_download_failed_dialog_title = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_download_failed_dialog_title;
			global::HockeyApp.Resource.String.hockeyapp_error_no_network_message = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_error_no_network_message;
			global::HockeyApp.Resource.String.hockeyapp_expiry_info_text = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_expiry_info_text;
			global::HockeyApp.Resource.String.hockeyapp_expiry_info_title = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_expiry_info_title;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attach_file = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_feedback_attach_file;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attach_picture = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_feedback_attach_picture;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attachment_button_text = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_feedback_attachment_button_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attachment_error = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_feedback_attachment_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attachment_loading = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_feedback_attachment_loading;
			global::HockeyApp.Resource.String.hockeyapp_feedback_email_hint = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_feedback_email_hint;
			global::HockeyApp.Resource.String.hockeyapp_feedback_failed_text = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_feedback_failed_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_failed_title = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_feedback_failed_title;
			global::HockeyApp.Resource.String.hockeyapp_feedback_fetching_feedback_text = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_feedback_fetching_feedback_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_generic_error = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_feedback_generic_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_last_updated_text = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_feedback_last_updated_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_max_attachments_allowed = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_feedback_max_attachments_allowed;
			global::HockeyApp.Resource.String.hockeyapp_feedback_message_hint = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_feedback_message_hint;
			global::HockeyApp.Resource.String.hockeyapp_feedback_name_hint = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_feedback_name_hint;
			global::HockeyApp.Resource.String.hockeyapp_feedback_refresh_button_text = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_feedback_refresh_button_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_response_button_text = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_feedback_response_button_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_select_file = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_feedback_select_file;
			global::HockeyApp.Resource.String.hockeyapp_feedback_select_picture = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_feedback_select_picture;
			global::HockeyApp.Resource.String.hockeyapp_feedback_send_button_text = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_feedback_send_button_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_send_generic_error = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_feedback_send_generic_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_send_network_error = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_feedback_send_network_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_sending_feedback_text = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_feedback_sending_feedback_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_subject_hint = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_feedback_subject_hint;
			global::HockeyApp.Resource.String.hockeyapp_feedback_title = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_feedback_title;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_email_empty = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_feedback_validate_email_empty;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_email_error = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_feedback_validate_email_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_name_error = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_feedback_validate_name_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_subject_error = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_feedback_validate_subject_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_text_error = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_feedback_validate_text_error;
			global::HockeyApp.Resource.String.hockeyapp_login_email_hint = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_login_email_hint;
			global::HockeyApp.Resource.String.hockeyapp_login_headline_text = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_login_headline_text;
			global::HockeyApp.Resource.String.hockeyapp_login_headline_text_email_only = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_login_headline_text_email_only;
			global::HockeyApp.Resource.String.hockeyapp_login_login_button_text = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_login_login_button_text;
			global::HockeyApp.Resource.String.hockeyapp_login_missing_credentials_toast = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_login_missing_credentials_toast;
			global::HockeyApp.Resource.String.hockeyapp_login_password_hint = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_login_password_hint;
			global::HockeyApp.Resource.String.hockeyapp_paint_dialog_message = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_paint_dialog_message;
			global::HockeyApp.Resource.String.hockeyapp_paint_dialog_negative_button = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_paint_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_paint_dialog_neutral_button = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_paint_dialog_neutral_button;
			global::HockeyApp.Resource.String.hockeyapp_paint_dialog_positive_button = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_paint_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_paint_indicator_toast = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_paint_indicator_toast;
			global::HockeyApp.Resource.String.hockeyapp_paint_menu_clear = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_paint_menu_clear;
			global::HockeyApp.Resource.String.hockeyapp_paint_menu_save = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_paint_menu_save;
			global::HockeyApp.Resource.String.hockeyapp_paint_menu_undo = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_paint_menu_undo;
			global::HockeyApp.Resource.String.hockeyapp_permission_dialog_negative_button = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_permission_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_permission_dialog_positive_button = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_permission_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_permission_update_message = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_permission_update_message;
			global::HockeyApp.Resource.String.hockeyapp_permission_update_title = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_permission_update_title;
			global::HockeyApp.Resource.String.hockeyapp_update_button = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_update_button;
			global::HockeyApp.Resource.String.hockeyapp_update_dialog_message = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_update_dialog_message;
			global::HockeyApp.Resource.String.hockeyapp_update_dialog_negative_button = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_update_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_update_dialog_positive_button = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_update_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_update_dialog_title = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_update_dialog_title;
			global::HockeyApp.Resource.String.hockeyapp_update_mandatory_toast = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_update_mandatory_toast;
			global::HockeyApp.Resource.String.hockeyapp_update_version_details_label = global::OxHack.Inventory.MobileClient.Droid.Resource.String.hockeyapp_update_version_details_label;
			global::HockeyApp.Resource.String.library_name = global::OxHack.Inventory.MobileClient.Droid.Resource.String.library_name;
			global::HockeyApp.Resource.Style.HockeyApp_ButtonStyle = global::OxHack.Inventory.MobileClient.Droid.Resource.Style.HockeyApp_ButtonStyle;
			global::HockeyApp.Resource.Style.HockeyApp_EditTextStyle = global::OxHack.Inventory.MobileClient.Droid.Resource.Style.HockeyApp_EditTextStyle;
			global::HockeyApp.Resource.Style.HockeyApp_SingleLineInputStyle = global::OxHack.Inventory.MobileClient.Droid.Resource.Style.HockeyApp_SingleLineInputStyle;
			global::Splat.Resource.String.library_name = global::OxHack.Inventory.MobileClient.Droid.Resource.String.library_name;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.actionBarSize = global::OxHack.Inventory.MobileClient.Droid.Resource.Attribute.actionBarSize;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int ahBarColor = 2130771971;
			
			// aapt resource value: 0x7f01000b
			public const int ahBarLength = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int ahBarWidth = 2130771978;
			
			// aapt resource value: 0x7f010008
			public const int ahCircleColor = 2130771976;
			
			// aapt resource value: 0x7f010007
			public const int ahDelayMillis = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int ahRadius = 2130771977;
			
			// aapt resource value: 0x7f010004
			public const int ahRimColor = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int ahRimWidth = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int ahSpinSpeed = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int ahText = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int ahTextColor = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int ahTextSize = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int hockeyapp_background_header = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int hockeyapp_background_light = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int hockeyapp_background_white = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int hockeyapp_button_background = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int hockeyapp_button_background_pressed = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int hockeyapp_button_background_selected = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int hockeyapp_text_black = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int hockeyapp_text_light = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int hockeyapp_text_normal = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int hockeyapp_text_white = 2131099657;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int hockeyapp_btn_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_errorstatus = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_successstatus = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int roundedbg = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int roundedbgdark = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000d
			public const int button_add_response = 2131165197;
			
			// aapt resource value: 0x7f070008
			public const int button_attachment = 2131165192;
			
			// aapt resource value: 0x7f070012
			public const int button_login = 2131165202;
			
			// aapt resource value: 0x7f07000e
			public const int button_refresh = 2131165198;
			
			// aapt resource value: 0x7f070009
			public const int button_send = 2131165193;
			
			// aapt resource value: 0x7f070016
			public const int button_update = 2131165206;
			
			// aapt resource value: 0x7f070004
			public const int input_email = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int input_message = 2131165190;
			
			// aapt resource value: 0x7f070003
			public const int input_name = 2131165187;
			
			// aapt resource value: 0x7f070011
			public const int input_password = 2131165201;
			
			// aapt resource value: 0x7f070005
			public const int input_subject = 2131165189;
			
			// aapt resource value: 0x7f070018
			public const int label_author = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int label_date = 2131165209;
			
			// aapt resource value: 0x7f07000b
			public const int label_last_updated = 2131165195;
			
			// aapt resource value: 0x7f070000
			public const int label_message = 2131165184;
			
			// aapt resource value: 0x7f07001a
			public const int label_text = 2131165210;
			
			// aapt resource value: 0x7f070014
			public const int label_title = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int label_version = 2131165205;
			
			// aapt resource value: 0x7f07001b
			public const int list_attachments = 2131165211;
			
			// aapt resource value: 0x7f07000f
			public const int list_feedback_messages = 2131165199;
			
			// aapt resource value: 0x7f07001e
			public const int loadingImage = 2131165214;
			
			// aapt resource value: 0x7f07001c
			public const int loadingProgressBar = 2131165212;
			
			// aapt resource value: 0x7f07001f
			public const int loadingProgressWheel = 2131165215;
			
			// aapt resource value: 0x7f07001d
			public const int textViewStatus = 2131165213;
			
			// aapt resource value: 0x7f070010
			public const int text_headline = 2131165200;
			
			// aapt resource value: 0x7f070013
			public const int view_header = 2131165203;
			
			// aapt resource value: 0x7f070017
			public const int web_update_details = 2131165207;
			
			// aapt resource value: 0x7f070007
			public const int wrapper_attachments = 2131165191;
			
			// aapt resource value: 0x7f070002
			public const int wrapper_feedback = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int wrapper_feedback_scroll = 2131165185;
			
			// aapt resource value: 0x7f07000a
			public const int wrapper_messages = 2131165194;
			
			// aapt resource value: 0x7f07000c
			public const int wrapper_messages_buttons = 2131165196;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int hockeyapp_activity_expiry_info = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int hockeyapp_activity_feedback = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int hockeyapp_activity_login = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int hockeyapp_activity_update = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int hockeyapp_fragment_update = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int hockeyapp_view_feedback_message = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int loading = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int loadingimage = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int loadingprogress = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int hockeyapp_crash_dialog_app_name_fallback = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int hockeyapp_crash_dialog_message = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int hockeyapp_crash_dialog_negative_button = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int hockeyapp_crash_dialog_neutral_button = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int hockeyapp_crash_dialog_positive_button = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int hockeyapp_crash_dialog_title = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int hockeyapp_dialog_error_message = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int hockeyapp_dialog_error_title = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int hockeyapp_dialog_negative_button = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int hockeyapp_dialog_positive_button = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int hockeyapp_download_failed_dialog_message = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int hockeyapp_download_failed_dialog_negative_button = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int hockeyapp_download_failed_dialog_positive_button = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int hockeyapp_download_failed_dialog_title = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int hockeyapp_error_no_network_message = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int hockeyapp_expiry_info_text = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int hockeyapp_expiry_info_title = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int hockeyapp_feedback_attach_file = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int hockeyapp_feedback_attach_picture = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int hockeyapp_feedback_attachment_button_text = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int hockeyapp_feedback_attachment_error = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int hockeyapp_feedback_attachment_loading = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int hockeyapp_feedback_email_hint = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int hockeyapp_feedback_failed_text = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int hockeyapp_feedback_failed_title = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int hockeyapp_feedback_fetching_feedback_text = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int hockeyapp_feedback_generic_error = 2130968603;
			
			// aapt resource value: 0x7f04001c
			public const int hockeyapp_feedback_last_updated_text = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int hockeyapp_feedback_max_attachments_allowed = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int hockeyapp_feedback_message_hint = 2130968606;
			
			// aapt resource value: 0x7f04001f
			public const int hockeyapp_feedback_name_hint = 2130968607;
			
			// aapt resource value: 0x7f040020
			public const int hockeyapp_feedback_refresh_button_text = 2130968608;
			
			// aapt resource value: 0x7f040021
			public const int hockeyapp_feedback_response_button_text = 2130968609;
			
			// aapt resource value: 0x7f040022
			public const int hockeyapp_feedback_select_file = 2130968610;
			
			// aapt resource value: 0x7f040023
			public const int hockeyapp_feedback_select_picture = 2130968611;
			
			// aapt resource value: 0x7f040024
			public const int hockeyapp_feedback_send_button_text = 2130968612;
			
			// aapt resource value: 0x7f040025
			public const int hockeyapp_feedback_send_generic_error = 2130968613;
			
			// aapt resource value: 0x7f040026
			public const int hockeyapp_feedback_send_network_error = 2130968614;
			
			// aapt resource value: 0x7f040027
			public const int hockeyapp_feedback_sending_feedback_text = 2130968615;
			
			// aapt resource value: 0x7f040028
			public const int hockeyapp_feedback_subject_hint = 2130968616;
			
			// aapt resource value: 0x7f040029
			public const int hockeyapp_feedback_title = 2130968617;
			
			// aapt resource value: 0x7f04002a
			public const int hockeyapp_feedback_validate_email_empty = 2130968618;
			
			// aapt resource value: 0x7f04002b
			public const int hockeyapp_feedback_validate_email_error = 2130968619;
			
			// aapt resource value: 0x7f04002c
			public const int hockeyapp_feedback_validate_name_error = 2130968620;
			
			// aapt resource value: 0x7f04002d
			public const int hockeyapp_feedback_validate_subject_error = 2130968621;
			
			// aapt resource value: 0x7f04002e
			public const int hockeyapp_feedback_validate_text_error = 2130968622;
			
			// aapt resource value: 0x7f04002f
			public const int hockeyapp_login_email_hint = 2130968623;
			
			// aapt resource value: 0x7f040030
			public const int hockeyapp_login_headline_text = 2130968624;
			
			// aapt resource value: 0x7f040031
			public const int hockeyapp_login_headline_text_email_only = 2130968625;
			
			// aapt resource value: 0x7f040032
			public const int hockeyapp_login_login_button_text = 2130968626;
			
			// aapt resource value: 0x7f040033
			public const int hockeyapp_login_missing_credentials_toast = 2130968627;
			
			// aapt resource value: 0x7f040034
			public const int hockeyapp_login_password_hint = 2130968628;
			
			// aapt resource value: 0x7f040035
			public const int hockeyapp_paint_dialog_message = 2130968629;
			
			// aapt resource value: 0x7f040036
			public const int hockeyapp_paint_dialog_negative_button = 2130968630;
			
			// aapt resource value: 0x7f040037
			public const int hockeyapp_paint_dialog_neutral_button = 2130968631;
			
			// aapt resource value: 0x7f040038
			public const int hockeyapp_paint_dialog_positive_button = 2130968632;
			
			// aapt resource value: 0x7f040039
			public const int hockeyapp_paint_indicator_toast = 2130968633;
			
			// aapt resource value: 0x7f04003a
			public const int hockeyapp_paint_menu_clear = 2130968634;
			
			// aapt resource value: 0x7f04003b
			public const int hockeyapp_paint_menu_save = 2130968635;
			
			// aapt resource value: 0x7f04003c
			public const int hockeyapp_paint_menu_undo = 2130968636;
			
			// aapt resource value: 0x7f04003d
			public const int hockeyapp_permission_dialog_negative_button = 2130968637;
			
			// aapt resource value: 0x7f04003e
			public const int hockeyapp_permission_dialog_positive_button = 2130968638;
			
			// aapt resource value: 0x7f04003f
			public const int hockeyapp_permission_update_message = 2130968639;
			
			// aapt resource value: 0x7f040040
			public const int hockeyapp_permission_update_title = 2130968640;
			
			// aapt resource value: 0x7f040041
			public const int hockeyapp_update_button = 2130968641;
			
			// aapt resource value: 0x7f040042
			public const int hockeyapp_update_dialog_message = 2130968642;
			
			// aapt resource value: 0x7f040043
			public const int hockeyapp_update_dialog_negative_button = 2130968643;
			
			// aapt resource value: 0x7f040044
			public const int hockeyapp_update_dialog_positive_button = 2130968644;
			
			// aapt resource value: 0x7f040045
			public const int hockeyapp_update_dialog_title = 2130968645;
			
			// aapt resource value: 0x7f040046
			public const int hockeyapp_update_mandatory_toast = 2130968646;
			
			// aapt resource value: 0x7f040047
			public const int hockeyapp_update_version_details_label = 2130968647;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int HockeyApp_ButtonStyle = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int HockeyApp_EditTextStyle = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int HockeyApp_SingleLineInputStyle = 2131034114;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ProgressWheel = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 3
			public const int ProgressWheel_ahBarColor = 3;
			
			// aapt resource value: 11
			public const int ProgressWheel_ahBarLength = 11;
			
			// aapt resource value: 10
			public const int ProgressWheel_ahBarWidth = 10;
			
			// aapt resource value: 8
			public const int ProgressWheel_ahCircleColor = 8;
			
			// aapt resource value: 7
			public const int ProgressWheel_ahDelayMillis = 7;
			
			// aapt resource value: 9
			public const int ProgressWheel_ahRadius = 9;
			
			// aapt resource value: 4
			public const int ProgressWheel_ahRimColor = 4;
			
			// aapt resource value: 5
			public const int ProgressWheel_ahRimWidth = 5;
			
			// aapt resource value: 6
			public const int ProgressWheel_ahSpinSpeed = 6;
			
			// aapt resource value: 0
			public const int ProgressWheel_ahText = 0;
			
			// aapt resource value: 1
			public const int ProgressWheel_ahTextColor = 1;
			
			// aapt resource value: 2
			public const int ProgressWheel_ahTextSize = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
